config/routes.rb
Rails.application.routes.draw do
  get 'conferences/new'

  get 'accounts/new'

  root to: 'conferences#index'
  get 'users/new'
  resources :users
  resources :calls
  resources :accounts
  resources :conferences
  resources :conferences do
    member do
      get :conf
      post :conf
    end
    resources :users do
      member do
        post :call
        get :call
      end
    end
  end
  resources :calls do
    member do
      post :drop
      get :drop
    end
  end
  resources :numbers
  resources :numbers do
    member do
      post :setactive
      get :setactive
    end
  end
  resources :users do
    member do
      post :call
      get :call
    end
  end
  resources :meet

end

app/models/conference.rb
class Conference < ActiveRecord::Base
#  attr_accessible :num
  validates :num, presence: true
  has_and_belongs_to_many :accounts
  has_and_belongs_to_many :users
  accepts_nested_attributes_for :accounts
  accepts_nested_attributes_for :users
  
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  def new
    @conference = Conference.new
  end
  def create
  	@conference = Conference.new(conference_params)
  	if @conference.save
  	  flash[:success] = "Conference added"
  	  redirect_to root_path
  	else
  		 render :action => :new
    end
  end
  def update
  	@conference = Conference.find(params[:id])
    
    if @conference.update_attributes(conference_params)
      #(params[:account])
    #  if @dhcpserver.lock = true
    #    @tftps = Tftp.all
    #    @dhcpserver.generate_config
    #    @dhcpserver.update_attributes(params[lock=false])
    #    flash[:success] = "Reconfigure OK"
    #    redirect_to main_path
    #  else
      
        flash[:success] = "Account updated"
        redirect_to conferences_path
    #  end
    else
      render :action => :edit
    end
  end
  def index
      @conferences = Conference.all
    end
    def conf
      @conference = Conference.find(params[:id])
      @users= @conference.users
      #@numbers= @users.numbers.all
      @calls = Call.all
      #@conference = Array.new
      @user = User.new
      @number = Number.new
      2.times { @user.numbers.build}
      @meet = Meet.first
    end
    def destroy
      Conference.find(params[:id]).destroy
      flash[:success] = "Conference deleted"
      redirect_to root_path
    end
    def edit
      @conference = Conference.find(params[:id])
    end
    private
    def conference_params
  	  params.require(:conference).permit( :num, account_ids: [], user_ids: [] )
    end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/views/conferences/conf.html.slim
.container
  .row
    .col-lg-12
      h3  Конфа #{@conference.num}
  .row
    .col-lg-12
      table.table.table-striped
        thead
          tr
            th.col-md-1
              = link_to new_user_path do
                span.glyphicon.glyphicon-plus.margin-left-7px
            th  Фио
            th
              = link_to new_number_path do
                span.glyphicon.glyphicon-plus.margin-left-7px
              |  Номера
            th  Управление звонком

            th.col-md-1  &nbsp;
        tbody
          - @users.each_with_index do |user, index|
            tr
              td
                span.margin-left-7px  = index + 1
              td  
                = user.name
                

              td
                - user.numbers.order("id DESC").each do |number| 
                  - if number.num.length > 4
                    span.glyphicon.glyphicon-phone.margin-left-7px
                  - else
                    span.glyphicon.glyphicon-phone-alt.margin-left-7px
                  = link_to setactive_number_path(number)
                    span.margin-left-7px  = number.num
                  = "   |   "
                  = link_to edit_number_path(number) do
                    span.glyphicon.glyphicon-pencil.margin-left-7px
                  = link_to number_path(number), :method => :delete, :class => :confirm_delete do
                    span.glyphicon.glyphicon-remove.margin-left-7p
                  - if number.active?
                    span.glyphicon.glyphicon-ok.margin-left-7px style="color: green"
                  
                  //= link_to call_number_path(number) do
                  //  span.glyphicon.glyphicon-forward.margin-right-77px

                  br
                    

              td    
                = link_to call_conference_user_path(@conference,user) do
                    span.glyphicon.glyphicon-earphone.margin-left-7px style="color: green"
                

              td
                = link_to edit_user_path(user) do
                  span.glyphicon.glyphicon-pencil.margin-left-7px
                = link_to user_path(user), :method => :delete, :class => :confirm_delete do
                  span.glyphicon.glyphicon-remove.margin-left-7px
  row
    .col-lg-12
      h3  Господа, которых уже вызвали
      = link_to root_path
        h5 Обновить
  .row
    .col-lg-12
      table.table.table-striped
        thead
          tr
            th 
            th Линия
            th Операция
        tbody
          - @calls.each_with_index do |call, index|
            tr
              td
                span.margin-left-7px  = index + 1
              td  
                = call.raw
              td    
                = link_to drop_call_path(call) do
                    span.glyphicon.glyphicon-earphone.margin-left-7px style="color: red; transform: rotate(180deg)"  

app/views/conferences/edit.html.slim
.container
  .row
    .col-lg-12
      h3
        = link_to "Конференции", conferences_path
        |  > Редактировать
  .row
    .col-lg-12
      = bootstrap_form_for @conference do |f|
        = f.text_field :num
        = collection_check_boxes(:conference, :account_ids, Account.all, :id, :name)
        = collection_check_boxes(:conference, :user_ids, User.all, :id, :name)
        = f.submit "Изменить"

app/views/conferences/edithtml.slim
.container
  .row
    .col-lg-12
      h3
        = link_to "Телефоны господ", root_path()
        |  > Поправить
  .row
    .col-lg-12
      = bootstrap_form_for @number do |f|
        = f.collection_select :user_id, @users, :id, :name
        = f.submit "Создать"

app/views/conferences/index.html.slim
.container
  .row
    .col-lg-12
      h3  Conferences
  .row
    .col-lg-12
      table.table.table-striped
        thead
          tr
            th.col-md-1
              = link_to new_conference_path do
                span.glyphicon.glyphicon-plus.margin-left-7px
            th  Номер конфы
            th  Господа в конфе
            th.col-md-1  &nbsp;
        tbody
          - @conferences.each_with_index do |conference, index|
            tr
              td
                span.margin-left-7px  = index + 1
              td  
                = link_to conference.num, conf_conference_path(conference)
                = link_to edit_conference_path(conference) do
                  span.glyphicon.glyphicon-pencil.margin-left-7px
                = link_to conference_path(conference), :method => :delete, :class => :confirm_delete do
                  span.glyphicon.glyphicon-remove.margin-left-7px
              
              td 
                - conference.users.each do |user|
                  = user.name
                  = " "

app/views/conferences/new.html.slim
.container
  .row
    .col-lg-12
      h3
        = link_to "Конференции", conferences_path
        |  > Новая
  .row
    .col-lg-12
      = bootstrap_form_for @conference do |f|
        = f.text_field :num
        - for account in Account.take(999)
            = check_box_tag "conference[account_ids][]", account.id, @conference.accounts.include?(account)
            = account.name
            = f.label " "
        = f.submit "Создать"