config/routes.rb
Rails.application.routes.draw do
  get 'conferences/new'

  get 'accounts/new'

  root to: 'conferences#index'
  get 'users/new'
  resources :users
  resources :calls
  resources :accounts
  resources :conferences
  resources :conferences do
    member do
      get :conf
      post :conf
    end
    resources :users do
      member do
        post :call
        get :call
      end
    end
  end
  resources :calls do
    member do
      post :drop
      get :drop
    end
  end
  resources :numbers
  resources :numbers do
    member do
      post :setactive
      get :setactive
    end
  end
  resources :users do
    member do
      post :call
      get :call
    end
  end
  resources :meet

end

app/views/layouts/_footer.html.slim
footer.footer
/  small
/    <a href="http://zayas.su/">z.DHCP</a>
/    by zayas
/  </small>
  nav
    ul
      li = link_to "About",   about_path %></li>

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "z.conference", root_path, id: "logo"
      nav
        ul class="nav pull-right"
        		li
                  = link_to "Acccouts", accounts_path
                li
                  = link_to "Conferences", conferences_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <%= render 'layouts/header' %>
    <div class="container">
<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

</body>
</html>