config/routes.rb
Rails.application.routes.draw do
  get 'conferences/new'

  get 'accounts/new'

  root to: 'conferences#index'
  get 'users/new'
  resources :users
  resources :calls
  resources :accounts
  resources :conferences
  resources :conferences do
    member do
      get :conf
      post :conf
    end
    resources :users do
      member do
        post :call
        get :call
      end
    end
  end
  resources :calls do
    member do
      post :drop
      get :drop
    end
  end
  resources :numbers
  resources :numbers do
    member do
      post :setactive
      get :setactive
    end
  end
  resources :users do
    member do
      post :call
      get :call
    end
  end
  resources :meet

end

app/models/account.rb
class Account < ActiveRecord::Base
#  attr_accessible :name, :email
  before_save { self.email = email.downcase }
  validates :name, presence: true
  validates :email, presence: true
  has_and_belongs_to_many :conferences
  accepts_nested_attributes_for :conferences
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
  @account = Account.new
  end
  def create
  	@account = Account.new(account_params)
  	if @account.save
  	  flash[:success] = "Account added"
  	  redirect_to root_path
  	else
  		 render :adction => :new
    end
  end
  def edit
   	@account = Account.find(params[:id])
  end
  def index
    @accounts = Account.all
#    @users= User.all
#    @numbers= Number.all
#    @calls = Call.all
    #@conference = Array.new
#    @user = User.new
#    @number = Number.new
#    2.times { @user.numbers.build}
#    @meet = Meet.first
  end

  def update
  	@account = Account.find(params[:id])
    
    if @account.update_attributes(account_params)
      #(params[:account])
    #  if @dhcpserver.lock = true
    #    @tftps = Tftp.all
    #    @dhcpserver.generate_config
    #    @dhcpserver.update_attributes(params[lock=false])
    #    flash[:success] = "Reconfigure OK"
    #    redirect_to main_path
    #  else
      
        flash[:success] = "Account updated"
        redirect_to accounts_path
    #  end
    else
      render :action => :edit
    end
  end
  def destroy
  	Account.find(params[:id]).destroy
  	flash[:success] = "Account deleted"
  	redirect_to root_path
  end

  private
  def account_params
  	params.require(:account).permit(:name,:email, conference_ids: [], conferences_attributes: [:account_id])
  end
  

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/edit.html.slim
.container
  .row
    .col-lg-12
      h3
        = link_to "Аккаунты", accounts_path
        |  > Новый
  .row
    .col-lg-12
      = bootstrap_form_for @account do |f|
        = f.text_field :name
        = f.text_field :email
        = collection_check_boxes(:account, :conference_ids, Conference.all, :id, :num)
        = f.submit "Изменить"

app/views/accounts/index.html.slim
.container
  .row
    .col-lg-12
      h3  Accounts
  .row
    .col-lg-12
      table.table.table-striped
        thead
          tr
            th.col-md-1
              = link_to new_account_path do
                span.glyphicon.glyphicon-plus.margin-left-7px
            th  Name
            th  Email
            th.col-md-1  &nbsp;
        tbody
          - @accounts.each_with_index do |account, index|
            tr
              td
                span.margin-left-7px  = index + 1
              td  
                = account.name
                

              td 
                = account.email
                = link_to edit_account_path(account) do
                  span.glyphicon.glyphicon-pencil.margin-left-7px
                = link_to account_path(account), :method => :delete, :class => :confirm_delete do
                  span.glyphicon.glyphicon-remove.margin-left-7px

app/views/accounts/new.html.slim
title= "New account"
h1 New account
.row
    .span6.offset3
      = form_for @account do |f|
        = f.label :email
        = f.text_field :email
        = f.label :name
        = f.text_field :name
        - for conference in Conference.find(:all)
            = check_box_tag "account[conference_ids][]", conference.id, @account.conferences.include?(conference)
            = conference.name
            = f.label " "
        = f.submit "Add new Account", class: "btn btn-large btn-primary"